version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookmarks
    networks:
      - learning
  test-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookmarks
    networks:
      - learning
networks: 
  learning: